### ISSUE TITLE
アーキテクチャ検討

### ISSUE THREAD

**Issue by mario031** [ht-swear/LifeGauge-ios#8]
ベースはVIPERを使用
ただ、既存のGenerambaで生成されるテンプレだとわかりにくいので、考える

**Comment by weeeeigen** [comment]
・Configurator使わないで，Routerでvcの初期化，次の画面への遷移をやる
・クラスの頭文字は大文字
・Output, InputはExtensionで書く

**Comment by weeeeigen** [comment]
他何かあったけ？ @mario031

**Comment by mario031** [comment]
- 共通の `View` は `Common/` におく
- Storyboard は Main 使用
- 特殊な実装をした時・実装上の背景がある時・あとで変更する可能性がある時等は、 コード上にコメント残しておく

**Comment by mario031** [comment]
@weeeeigen  まあ、あとは書きながらだね
あとで Readme.md か scrapbox あたりにまとめとくわ
